theme: jekyll-theme-minimal
title: "Decoding the Silver Screen: Key Drivers of Cinematic Success"
description: "An analysis of key factors to critical and commercial successes in the movie industry over time."
show_downloads: True


